### ISSUE TITLE
ld: library not found for -lCHTTPParser for architecture x86_64

### ISSUE THREAD

**Issue by adnanzzz11** [IBM/swift-kitura-helloworld#1]
Linking ./.build/debug/kituraHelloworld
ld: library not found for -lCHTTPParser for architecture x86_64

When you try to do a swift build, you get the following error

**Comment by kostickm** [comment]
@adnanzzz11 I ran the tutorial on both macOS and Ubuntu without seeing the issue above using Swift 3.1.1. I would double check your versions and that the latest Swift is in your path.

**Comment by adnanzzz11** [comment]
There was a problem with the Swift version, Thank you!

**Comment by kostickm** [comment]
@adnanzzz11 No problem!
